flaskapp/blueprints/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms import TextAreaField
from wtforms.validators import DataRequired
from wtforms.validators import Email
from wtforms.validators import Length


class ContactUs(FlaskForm):
    name = StringField("Name",
                       validators=[DataRequired(),
                                   Length(min=2, max=20)])
    email = StringField("Email", validators=[DataRequired(), Email()])
    mobile = StringField("Mobile", validators=[Length(4, 16)])
    subject = StringField("Subject",
                          validators=[DataRequired(),
                                      Length(5, 200)])
    message = TextAreaField("Message",
                            validators=[DataRequired(),
                                        Length(5, 10000)])

flaskapp/__init__.py
import os

from flask import Flask
from flask_bcrypt import Bcrypt
from flask_caching import Cache
from flask_login import LoginManager
from flask_mail import Mail
from flask_minify import minify
from flask_sqlalchemy import SQLAlchemy

from flaskapp.config import Config

db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = "users.login"
login_manager.login_message_category = "info"
mail = Mail()
cache = Cache()
APP_PATH = os.path.dirname(os.path.abspath(__file__))
TEST_DB = "test.db"


def create_app(config_class=Config):
    """To create

    Keyword Arguments:
        config_class {object} -- It configures app (default: {Config})

    Returns:
        App -- it creates app using configuration from config_class
    """
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    cache.init_app(app)
    minify(app=app, html=True, js=True, cssless=True)

    from flaskapp.blueprints.users.routes import users
    from flaskapp.blueprints.courses.routes import courses
    from flaskapp.blueprints.questions.routes import questions
    from flaskapp.blueprints.main.routes import main
    from flaskapp.blueprints.errors.routes import errors
    from flaskapp.blueprints.papers.routes import papers

    app.register_blueprint(users)
    app.register_blueprint(courses)
    app.register_blueprint(questions)
    app.register_blueprint(main)
    app.register_blueprint(errors)
    app.register_blueprint(papers)

    return app

flaskapp/blueprints/__init__.py
"""blueprints for the application"""

flaskapp/blueprints/courses/__init__.py
"""course blueprint"""

flaskapp/blueprints/courses/routes.py
from flask import Blueprint
from flask import flash
from flask import render_template
from flask import request
from flask import url_for
from flask_login import current_user
from flask_login import login_required
from werkzeug.utils import redirect

from flaskapp import db
from flaskapp.blueprints.courses.forms import CourseForm
from flaskapp.blueprints.courses.forms import UnitForm
from flaskapp.checkers import check_valid_course
from flaskapp.models import Course
from flaskapp.models import Unit
from flaskapp.utils import profile_path

courses = Blueprint("courses", __name__)


@courses.route("/course/new/", methods=["GET", "POST"])
@login_required
def add_course():
    """Rendering to add course page

    Returns:
        HTML function -- For adding new course to user's account. After submitting new course redirect to courses page.Else show form which
        shows add course feild.
    """
    form = CourseForm()
    if form.validate_on_submit():
        _course = Course(name=form.course.data, teacher=current_user)
        db.session.add(_course)
        db.session.commit()
        flash("New course added successfully!", "success")
        return redirect(url_for("courses.all_courses"))
    return render_template(
        "course/course_form.html",
        form=form,
        css_files=["css/base.css", "css/course/courses_form.css"],
        js_files=["js/course/add_course.js"],
        image_file=profile_path(),
        title="Add Courses",
    )


@courses.route("/course/")
@login_required
def all_courses():
    """Show listed down course of user

    Returns:
        HTML function -- Redirect to courses pages where listed down all courses.
    """
    _courses = Course.query.filter(Course.teacher == current_user).all()
    return render_template(
        "course/courses.html",
        courses=_courses,
        css_files=["css/base.css", "css/course/courses.css"],
        js_files=["js/course/remove_course.js"],
        image_file=profile_path(),
        title="Courses",
    )


@courses.route("/course/delete/", methods=["GET", "POST"])
@login_required
def delete_course():
    """Delete course from list of courses
    """
    if request.method == "POST":
        course_ids = request.get_json()
        db.session.query(Course).filter(
            Course.id.in_(course_ids)).delete(synchronize_session="fetch")
        db.session.commit()
    return redirect(url_for("courses.all_courses"))


@courses.route("/course/<course_id>/unit/")
@login_required
@check_valid_course
def all_units(course_id):
    """Give all units list of course with given course ID

    Args:
        course_id (int): Course ID of Course

    Returns:
        HTML: returns question page for course
    """
    _course = Course.query.filter(Course.id == course_id).first()
    _units = Unit.query.filter(Unit.course == _course).all()
    return render_template(
        "course/units.html",
        course_id=course_id,
        image_file=profile_path(),
        units=_units,
        title="Units",
        css_files=["css/base.css", "css/course/courses.css"],
        js_files=["js/course/remove_course.js"],
    )


@courses.route("/course/<course_id>/unit/new", methods=["GET", "POST"])
@login_required
@check_valid_course
def add_unit(course_id):
    """Add unit to course

    Args:
        course_id (int): ID of course

    Returns:
        HTML: Go to question of units template
    """
    _course = Course.query.filter(Course.id == course_id).first()
    form = UnitForm(_course)
    if form.validate_on_submit():
        unit = Unit(chapter_no=form.chapter_no.data,
                    name=form.name.data,
                    course=_course)
        db.session.add(unit)
        db.session.commit()
        flash("New unit added successfully!", "success")
        return redirect(url_for("courses.all_units", course_id=course_id))
    return render_template(
        "course/unit_form.html",
        course_id=course_id,
        form=form,
        css_files=["css/base.css", "css/course/courses_form.css"],
        js_files=["js/course/add_unit.js"],
        image_file=profile_path(),
        title="Add Units",
    )


@courses.route("/course/<course_id>/unit/delete/", methods=["GET", "POST"])
@login_required
@check_valid_course
def delete_unit(course_id):
    """Delete unit for given course

    Args:
        course_id (int): Course id which user want to delete
    """
    if request.method == "POST":
        unit_ids = request.get_json()
        db.session.query(Unit).filter(
            Unit.id.in_(unit_ids)).delete(synchronize_session="fetch")
        db.session.commit()
    return redirect(url_for("courses.all_units", course_id=course_id))

flaskapp/blueprints/main/__init__.py
"""main blueprint"""

flaskapp/blueprints/papers/__init__.py
"""papers blueprint"""

flaskapp/blueprints/questions/__init__.py
"""questions blueprint"""

flaskapp/blueprints/questions/routes.py
from flask import Blueprint
from flask import flash
from flask import render_template
from flask import request
from flask_login import current_user
from flask_login import login_required
from sqlalchemy import and_

from flaskapp import db
from flaskapp.blueprints.questions.forms import MCQQuestionForm
from flaskapp.blueprints.questions.forms import QuestionForm
from flaskapp.blueprints.questions.utils import add_question_to_db
from flaskapp.blueprints.questions.utils import delete_question_from_db
from flaskapp.blueprints.questions.utils import redirect_to_all_questions
from flaskapp.blueprints.questions.utils import update_imp_in_db
from flaskapp.blueprints.questions.utils import update_question_in_db
from flaskapp.checkers import check_valid_course
from flaskapp.checkers import check_valid_question_type
from flaskapp.checkers import check_valid_unit
from flaskapp.models import Course
from flaskapp.models import Question
from flaskapp.utils import profile_path
from flaskapp.utils import QuestionTypeEnum

questions = Blueprint("questions", __name__)


@questions.route("/course/<course_id>/unit/<unit_id>/question/<qtype>/")
@login_required
@check_valid_course
@check_valid_unit
@check_valid_question_type
def all_questions(course_id, unit_id, qtype):
    """Rendering Question page
    Arguments:
        course_id {Object} -- Id for course
        qtype {Subjective/mcq} -- Specification about question is subjective or MCQ type
    Returns:
        HTML Function -- According to chosen type of question render page
    """
    main_page = request.args.get("page", 1, type=int)
    _courses = Course.query.filter(Course.teacher == current_user).all()
    _questions = Question.query.filter(
        and_(
            Question.unit_id == unit_id,
            Question.question_type == QuestionTypeEnum.from_string(qtype),
        )).paginate(page=main_page, per_page=10)
    common_args = dict(
        courses=_courses,
        course_id=course_id,
        unit_id=unit_id,
        qtype=qtype,
        image_file=profile_path(),
    )
    if qtype == "mcq":
        return render_template(
            "questions/mcq_questions.html",
            questions=_questions,
            css_files=[
                "css/base.css",
                "css/questions/mcqs.css",
                "css/sideNav.css",
                "css/questions/questions.css",
                "css/questions/mcq_form.css",
                "css/questions/question_form.css",
            ],
            js_files=["js/questions/update_mcq_question.js", "js/sideNav.js"],
            title="Objective Questions",
            **common_args,
        )
    else:
        return render_template(
            "questions/questions.html",
            questions=_questions,
            css_files=[
                "css/base.css",
                "css/questions/questions.css",
                "css/sideNav.css",
                "css/questions/question_form.css",
            ],
            js_files=[
                "js/questions/update_question.js",
                "js/sideNav.js",
            ],
            title="Subjective Questions",
            **common_args,
        )


@questions.route(
    "/course/<course_id>/unit/<unit_id>/question/<qtype>/new/",
    methods=["GET", "POST"],
)
@login_required
@check_valid_course
@check_valid_unit
@check_valid_question_type
def add_question(course_id, unit_id, qtype):
    """Adding question
    Arguments:
        course_id {Object} -- Course ID which uniquely defined.
        question_type {Subjective/MCQ} -- What is the type of question ? subjective or MCQ

    Returns:
        HTML function -- If the course instructor is not user than it will throw error 403 then
        according to type of question eg : if type is MCQ then difficulty, mark, options, IMP flag
        and if type is subjective then difficulty,mark,IMP flag added with question to the database
        and will add to UI and list down on screen.
    """
    _courses = Course.query.filter(Course.teacher == current_user).all()
    common_args = dict(
        courses=_courses,
        course_id=course_id,
        unit_id=unit_id,
        qtype=qtype,
        image_file=profile_path(),
    )
    if qtype == "mcq":
        form = MCQQuestionForm()
        if form.validate_on_submit():
            question = dict(
                question=form.question.data,
                option1=form.option1.data,
                option2=form.option2.data,
                option3=form.option3.data,
                option4=form.option4.data,
            )
            flash("New question added successfully!", "success")
            add_question_to_db(form, question, unit_id, qtype)
            return redirect_to_all_questions(course_id, unit_id, qtype)
        return render_template(
            "questions/mcq_question_form.html",
            form=form,
            css_files=[
                "css/base.css",
                "css/questions/mcq_form.css",
                "css/sideNav.css",
                "css/questions/question_form.css",
            ],
            js_files=["js/questions/mcq_question_form.js", "js/sideNav.js"],
            title="Add Objective Question",
            **common_args,
        )
    else:
        form = QuestionForm()
        if form.validate_on_submit():
            question = dict(question=form.question.data)
            flash("New question added successfully!", "success")
            add_question_to_db(form, question, unit_id, qtype)
            return redirect_to_all_questions(course_id, unit_id, qtype)
        return render_template(
            "questions/question_form.html",
            form=form,
            css_files=[
                "css/base.css",
                "css/questions/question_form.css",
                "css/sideNav.css",
            ],
            js_files=["js/questions/question_form.js", "js/sideNav.js"],
            title="Add Subjective Question",
            **common_args,
        )


@questions.route(
    "/course/<course_id>/unit/<unit_id>/question/<qtype>/update/<int:question_id>/",
    methods=["GET", "POST"],
)
@login_required
@check_valid_course
@check_valid_unit
@check_valid_question_type
def update_question(course_id, unit_id, qtype, question_id):
    """For updating question
    Returns:
        Render template -- for updating questions if that question is exist then update it by id.And update marks , difficulty and IMP flag accorging to input.
       And do changes in database accordingly.
    """
    common_args = dict(
        course_id=course_id,
        unit_id=unit_id,
        qtype=qtype,
        image_file=profile_path(),
    )
    _question = db.session.query(Question).filter_by(id=question_id).first()
    if _question is None:
        flash(f"Question:{question_id} Does not exist", "Failure")
        return redirect_to_all_questions(course_id, unit_id, qtype)
    data = _question.to_dict()
    data.update(_question.question)
    if qtype == "mcq":
        form = MCQQuestionForm(**data)
        if form.validate_on_submit():
            _question.question = dict(
                question=form.question.data,
                option1=form.option1.data,
                option2=form.option2.data,
                option3=form.option3.data,
                option4=form.option4.data,
            )
            update_question_in_db(form, _question, qtype)
            flash(f"Question:{question_id} updated successfully!", "success")
            return redirect_to_all_questions(course_id, unit_id, qtype)
        return render_template(
            "questions/mcq_question_form.html",
            form=form,
            css_files=["css/questions/question_form.css"],
            js_files=["js/questions/question_form.js"],
            **common_args,
        )
    else:
        form = QuestionForm(**data)
        if form.validate_on_submit():
            _question.question = dict(question=form.question.data)
            update_question_in_db(form, _question, qtype)
            flash(f"Question:{question_id} updated successfully!", "success")
            return redirect_to_all_questions(course_id, unit_id, qtype)
        return render_template(
            "questions/question_form.html",
            form=form,
            css_files=["css/questions/question_form.css"],
            js_files=["js/questions/question_form.js"],
            **common_args,
        )


@questions.route("/course/<course_id>/unit/<unit_id>/question/<qtype>/imp/",
                 methods=["GET", "POST"])
@login_required
@check_valid_course
@check_valid_unit
@check_valid_question_type
def imp_question(course_id, unit_id, qtype):
    """Set an IMP flag to question
    Returns:
        Same page with flag or without flag -- set an IMP flag to particular question.And do changes in database also.
    """
    if request.method == "POST":
        update_imp_in_db(request.get_json())
        return redirect_to_all_questions(course_id, unit_id, qtype)


@questions.route(
    "/course/<course_id>/unit/<unit_id>/question/<qtype>/delete/",
    methods=["GET", "POST"],
)
@login_required
@check_valid_course
@check_valid_unit
@check_valid_question_type
def delete_question(course_id, unit_id, qtype):
    """Delete question
    Returns:
        page -- If current user is not an instructor of that subject then throw erroe else
        delete question's data. and update UI.
    """

    if request.method == "POST":
        delete_question_from_db(request.get_json())
        return redirect_to_all_questions(course_id, unit_id, qtype)

flaskapp/blueprints/users/__init__.py
"""users blueprint"""

flaskapp/templates/questions/mcq_questions.html
{% extends "sideNav.html" %}

{% block header %}
    <h1 class="header">Multiple Choice Question</h1>
{% endblock header %}

{% block flashes %}

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
messages %}

        <ul class="flashes flashes_question">
            {% for category, message in messages %}
                <li class="{{ category }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %} {% endwith %}

{% endblock flashes %}

{% block main %}
    <div id="questions">
        {% block content %}
            <div class="control_btns">
                <div id="mark_imp" title="update imp">
                    <img src="{{ url_for('static',
                filename='images/imp.svg') }}" alt="imp"
                         class="control_btns_img"/>
                </div>

                <div id="delete_btn" title="delete">
                    <img src="{{ url_for('static',
                filename='images/bin.png') }}" alt="delete"
                         class="control_btns_img"/>
                </div>
                <div id="cancel_btn" title="Cancel">
                    <img src="{{ url_for('static',
                filename='images/cancel.svg') }}" alt="cancel"
                         class="control_btns_img"/>
                </div>
            </div>
            <div>
            {% for q in questions.items %}
                <div class="question_container">
                    <div class="delete_question">
                        <label><input type="checkbox" class="delete_checkbox"/></label>
                    </div>
                    <div class="question_info">
                        <div class="first_row">
                            <div class="first_row_column_1" data-id="{{ q.id }}"></div>
                            <div class="first_row_column_2">

                                {{ q.imp }}</div>
                            <div class="first_row_column_3">
                                <label><span class="mark_label"></span><input
                                        type="checkbox" name="isimp" value="false"
                                        class="imp_checkbox"/></label>
                            </div>
                        </div>

                        <div class="second_row">
                            <div><span class="left">Marks</span>:
                                <span class="marks">{{ q.mark }}</span></div>
                        </div>
                        <div class="third_row">
                            <div><span class="left">Difficulty</span>:
                                <span class="difficulty">{{ q.difficulty }}</span></div>
                        </div>
                        <div class="fourth_row">
                            <div><span class="left">Cognitive
                            level</span>: <span class="cognitive"> {{ q.cognitive_level }}</span></div>
                        </div>
                        <div class="fifth_row">
                            <span class="left">Question</span>:
                            <div class="question_description">
                                {{ q.question.question }}
                            </div>
                        </div>


                        <div class="options_container">
                            <div class="options_final_value">{{ q.question.option1 }}</div>
                            <div class="options_final_value">{{ q.question.option2 }}</div>
                            <div class="options_final_value">{{ q.question.option3 }}</div>
                            <div class="options_final_value">{{ q.question.option4 }}</div>
                        </div>

                    </div>
                    <div class="update_question">
                        <div class="edit_question">
                            <img src="{{ url_for('static',
                        filename='images/edit.png') }}" alt="edit"
                                 class="update_question_img"/>
                        </div>

                    </div>
                </div>

            {% endfor %}



        {% endblock %}


        </div>
    </div>
{% endblock %}

{% block page %}
    {% if questions %}
        <div id="pagination">
            {% for page_num in questions.iter_pages(left_edge=1,
    right_edge=1,
    left_current=1,
    right_current=2) %}
                {% if page_num %}
                    {% if questions.page == page_num %}
                        <a class="btn btn-info mb-4" href="{{ url_for('questions.all_questions',
        page=page_num,
        course_id=course_id, unit_id=unit_id,
        qtype=qtype) }}">{{ page_num }}</a>
                    {% else %}
                        <a class="btn btn-outline-info mb-4" href="{{ url_for('questions.all_questions',
        page=page_num,
        course_id=course_id, unit_id=unit_id,

        qtype=qtype) }}">{{ page_num }}</a>
                    {% endif %}

                {% else %}
                    ...
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

flaskapp/templates/questions/question_form.html
{% extends "sideNav.html" %}

{% block header %}
<h3 class="header">Add Subjective Question</h3>
{% endblock header %}

{% block flashes %}
{% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %}
<ul class="flashes">
    {% for category, message in messages %}
    <li class="{{ category }}">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %} {% endwith %}
{% endblock flashes %}
{% block main %}
<div id="new_question">

    <form method="POST" action="" novalidate id="form">

        {{ form.hidden_tag() }}

        <div id="form_content">
            <div class="form_field_question_label">
                {{ form.question.label }} :
                <div>
                    {{ form.question(id="form_field_question_value") }}
                </div>
                {% if form.question.errors %}
                <ul class="form__error">
                    {% for error in form.question.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <div class="form__client_error"></div>
            </div>
            <div class="form_attributes">
                <div id="marks_label">
                    {{ form.mark.label }} :
                    <div>
                        {{ form.mark(id="marks_value") }}
                    </div>
                    {% if form.mark.errors %}
                    <ul class="form__error">
                        {% for error in form.mark.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    <div class="form__client_error"></div>
                </div>
                <div id="difficulty_label">
                    {{ form.difficulty.label }} :
                    <div>
                        {{ form.difficulty(id="difficulty_value") }}
                    </div>
                </div>

            </div>
            <div class="form_attributes">
                <div id="cognitive_label">
                    {{ form.cognitive_level.label }} :
                    <div>
                        {{ form.cognitive_level(id="cognitive_value") }}
                    </div>
                </div>
            </div>

            <div class="form__fields">
                {{ form.imp.label(id="mark_as_imp") }}
                {{ form.imp(id="imp_checkbox") }}
                <div id="toggle_container">
                    <div id="toggle_btn"></div>
                </div>
                Always include in Papers
            </div>
            <div id="submit_reset_container">
                {{ form.submit(id="submit_btn") }}
                <button type="reset" id="reset_btn">Cancel</button>
            </div>
        </div>
    </form>

</div>
{% endblock main %}

flaskapp/templates/questions/questions.html
{% extends "sideNav.html" %}

{% block header %}
<h1 class="header">Subjective Questions</h1>
{% endblock header %}

{% block flashes %}
{% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %}
<ul class="flashes flashes_question">
    {% for category, message in messages %}
    <li class="{{ category }}">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %} {% endwith %}
{% endblock flashes %}

{% block main %}
<div id="questions">
    {% block content %}
    <div class="control_btns">
        <div id="mark_imp" title="mark imp">
            <img src="{{ url_for('static',
                filename='images/imp.svg') }}" alt="imp" class="control_btns_img" />
        </div>

        <div id="delete_btn" title="delete">
            <img src="{{ url_for('static',
                filename='images/bin.png') }}" alt="delete" class="control_btns_img" />
        </div>

        <div id="cancel_btn" title="Cancel">
            <img src="{{ url_for('static',
                filename='images/cancel.svg') }}" alt="cancel" class="control_btns_img" />
        </div>

    </div>
    <div>

        {% for q in questions.items %}
        <div class="question_container">
            <div class="delete_question">
                <label><input type="checkbox" class="delete_checkbox" /></label>
            </div>
            <div class="question_info">
                <div class="first_row">
                    <div class="first_row_column_1" data-id="{{ q.id }}"></div>
                    <div class="first_row_column_2">

                        {{ q.imp }}</div>
                    <div class="first_row_column_3">
                        <label><span class="mark_label"></span><input type="checkbox" name="isimp" value="false"
                                class="imp_checkbox" /></label>
                    </div>
                </div>
                <div class="second_row">
                    <div><span class="left">Marks</span>:
                        <span class="marks">{{ q.mark }}</span></div>
                </div>
                <div class="third_row">
                    <div><span class="left">Difficulty</span>:
                        <span class="difficulty">{{ q.difficulty }}</span></div>
                </div>
                <div class="fourth_row">
                    <div><span class="left">Cognitive
                            level</span>: <span class="cognitive"> {{
                            q.cognitive_level }}</span></div>
                </div>
                <div class="fifth_row">
                        <span class="left">Question</span>: <div class="question_description">
                            {{ q.question.question }}
                        </div>
                </div>

            </div>
            <div class="update_question">
                <div class="edit_question">
                    <img src="{{ url_for('static',
                    filename='images/edit.png') }}" alt="edit" class="update_question_img" />
                </div>
            </div>
        </div>

        {% endfor %} {% endblock %}


    </div>
</div>
{% endblock %}
{% block page %}
{% if questions %}
<div id="pagination">
    {% for page_num in questions.iter_pages(left_edge=1,
                                                right_edge=1,
                                                left_current=1,
                                                right_current=2) %}
    {% if page_num %}
    {% if questions.page == page_num %}
    <a class="btn btn-info mb-4"
        href="{{ url_for('questions.all_questions', page=page_num, course_id=course_id, unit_id=unit_id, qtype=qtype) }}">{{ page_num }}</a>
    {% else %}
    <a class="btn btn-outline-info mb-4"
        href="{{ url_for('questions.all_questions', page=page_num, course_id=course_id, unit_id=unit_id, qtype=qtype) }}">{{ page_num }}</a>
    {% endif %}
    {% else %}
    ...
    {% endif %}
    {% endfor %}
</div>
{% endif %}
{% endblock %}